# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anduin Component Library
email: design@anduintransact.com
description: > # this means to ignore newlines until "baseurl:"
  Reasonable System for CSS Stylesheet Structure. A set of simple ideas
  to guide your process of building maintainable CSS.
baseurl: "" # the subpath of your site, e.g. /blog
version: 1.0.10
url: "https://anduintransact.com" # the base hostname & protocol for your site
twitter_username: anduintransact
github_username:  anduintransact

# Collections
collections:
    docs:
        output: true
    misc:
        output: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

sass:
  sass_dir: sass
